/**
 * Chief Complaints Seed Data
 *
 * Complete seed data for 150+ chief complaints organized by 18 macro groups.
 * Based on emergency medicine triage systems and Brazilian medical practice.
 */

import { TagCategory } from '@prisma/client'

interface ChiefComplaintTagSeed {
  category: TagCategory
  value: string
}

export interface ChiefComplaintSeed {
  code: string
  groupCode: string
  namePt: string
  nameEn?: string
  definition?: string
  synonyms: string[]
  icd10Codes: string[]
  isTimeSensitive: boolean
  isHighAcuity: boolean
  requiresIsolation?: boolean
  tags: ChiefComplaintTagSeed[]
  defaultCalculatorId?: string
  legacySyndromeCode?: string
  clinicalFlow?: unknown
}

// ============================================
// CV - CARDIOVASCULAR
// ============================================

export const CARDIOVASCULAR_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'CV_CHEST_PAIN_TYPICAL',
    groupCode: 'CV',
    namePt: 'Dor Toracica Tipica',
    nameEn: 'Typical Chest Pain',
    definition: 'Dor toracica com caracteristicas sugestivas de sindrome coronariana aguda: dor precordial em aperto/pressao, irradiacao para MSE/mandibula, associada a dispneia/sudorese',
    synonyms: ['precordialgia', 'dor no peito', 'dor toracica', 'aperto no peito', 'peso no peito', 'angina'],
    icd10Codes: ['I20.9', 'R07.9', 'I21.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.SYNDROME, value: 'acute_coronary_syndrome' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'heart-score',
    legacySyndromeCode: 'CHEST_PAIN',
  },
  {
    code: 'CV_CHEST_PAIN_ATYPICAL',
    groupCode: 'CV',
    namePt: 'Dor Toracica Atipica',
    nameEn: 'Atypical Chest Pain',
    definition: 'Dor toracica sem caracteristicas tipicas de SCA: dor ventilatoria-dependente, bem localizada, reprodutivel a palpacao',
    synonyms: ['dor toracica ventilatoria', 'dor pleuritica', 'dor musculoesqueletica'],
    icd10Codes: ['R07.9', 'R07.4'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
    defaultCalculatorId: 'heart-score',
    legacySyndromeCode: 'CHEST_PAIN',
  },
  {
    code: 'CV_PALPITATIONS',
    groupCode: 'CV',
    namePt: 'Palpitacoes',
    nameEn: 'Palpitations',
    definition: 'Sensacao de batimento cardiaco irregular, acelerado ou forte. Pode estar associada a arritmias ou ansiedade.',
    synonyms: ['coracao acelerado', 'taquicardia', 'arritmia', 'batedeira', 'coracao disparado', 'palpitacao'],
    icd10Codes: ['R00.2', 'R00.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'cha2ds2-vasc',
  },
  {
    code: 'CV_SYNCOPE',
    groupCode: 'CV',
    namePt: 'Sincope',
    nameEn: 'Syncope',
    definition: 'Perda transitoria de consciencia com recuperacao espontanea completa. Pode ter etiologia cardiaca, neurologica ou vasovagal.',
    synonyms: ['desmaio', 'perda de consciencia', 'desmaiou', 'apagou', 'lipotimia', 'desfalecimento'],
    icd10Codes: ['R55'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'cha2ds2-vasc',
  },
  {
    code: 'CV_HYPERTENSIVE_CRISIS',
    groupCode: 'CV',
    namePt: 'Crise Hipertensiva',
    nameEn: 'Hypertensive Crisis',
    definition: 'Elevacao acentuada da pressao arterial (geralmente PAS > 180 e/ou PAD > 120), com ou sem lesao de orgao-alvo.',
    synonyms: ['pressao alta', 'pico de pressao', 'hipertensao', 'emergencia hipertensiva', 'urgencia hipertensiva'],
    icd10Codes: ['I10', 'I16.0', 'I16.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'map',
  },
  {
    code: 'CV_EDEMA_LOWER_LIMBS',
    groupCode: 'CV',
    namePt: 'Edema de Membros Inferiores',
    nameEn: 'Lower Limb Edema',
    definition: 'Inchaço das pernas, podendo ser unilateral (TVP, celulite) ou bilateral (ICC, sindrome nefrotica).',
    synonyms: ['pernas inchadas', 'inchaço nas pernas', 'edema', 'pernas pesadas'],
    icd10Codes: ['R60.0', 'R60.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'wells-dvt',
  },
  {
    code: 'CV_ACUTE_PULMONARY_EDEMA',
    groupCode: 'CV',
    namePt: 'Edema Agudo de Pulmao',
    nameEn: 'Acute Pulmonary Edema',
    definition: 'Acumulo rapido de liquido nos alveolos pulmonares, geralmente por descompensacao de insuficiencia cardiaca.',
    synonyms: ['falta de ar aguda', 'dispneia cardiaca', 'congestao pulmonar', 'ICC descompensada'],
    icd10Codes: ['J81', 'I50.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'cardiovascular' },
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.SYNDROME, value: 'respiratory_failure' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
]

// ============================================
// RC - RESPIRATORIO
// ============================================

export const RESPIRATORY_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'RC_DYSPNEA_ACUTE',
    groupCode: 'RC',
    namePt: 'Dispneia Aguda',
    nameEn: 'Acute Dyspnea',
    definition: 'Falta de ar de inicio subito ou rapidamente progressiva, requerendo avaliacao imediata.',
    synonyms: ['falta de ar', 'dificuldade para respirar', 'cansaco', 'dispneia', 'sufocamento', 'fôlego curto'],
    icd10Codes: ['R06.0', 'R06.02'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.SYNDROME, value: 'respiratory_failure' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'wells-pe',
    legacySyndromeCode: 'DYSPNEA',
  },
  {
    code: 'RC_DYSPNEA_CHRONIC_EXAC',
    groupCode: 'RC',
    namePt: 'Exacerbacao de Dispneia Cronica',
    nameEn: 'Chronic Dyspnea Exacerbation',
    definition: 'Piora aguda de dispneia em paciente com doenca respiratoria cronica (DPOC, asma, fibrose).',
    synonyms: ['piora da falta de ar', 'dpoc descompensado', 'asma', 'crise asmatica', 'broncoespasmo'],
    icd10Codes: ['J44.1', 'J45.9', 'J96.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'curb-65',
    legacySyndromeCode: 'DYSPNEA',
  },
  {
    code: 'RC_COUGH_PRODUCTIVE',
    groupCode: 'RC',
    namePt: 'Tosse Produtiva',
    nameEn: 'Productive Cough',
    definition: 'Tosse com producao de secrecao/expectoracao. Pode indicar infeccao respiratoria.',
    synonyms: ['tosse com catarro', 'tosse produtiva', 'expectoracao', 'catarro', 'escarro'],
    icd10Codes: ['R05', 'R09.3'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'curb-65',
  },
  {
    code: 'RC_HEMOPTYSIS',
    groupCode: 'RC',
    namePt: 'Hemoptise',
    nameEn: 'Hemoptysis',
    definition: 'Tosse com sangue ou expectoracao sanguinolenta. Pode indicar TEP, TB, neoplasia ou infeccao.',
    synonyms: ['tosse com sangue', 'sangue na tosse', 'escarro com sangue', 'cuspir sangue'],
    icd10Codes: ['R04.2'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'wells-pe',
  },
  {
    code: 'RC_WHEEZING',
    groupCode: 'RC',
    namePt: 'Sibilancia / Chiado',
    nameEn: 'Wheezing',
    definition: 'Som agudo durante a respiracao, geralmente associado a broncoespasmo ou obstrucao.',
    synonyms: ['chiado no peito', 'sibilo', 'pulmao chiando', 'bronquite', 'asma'],
    icd10Codes: ['R06.2'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'RC_RESPIRATORY_FAILURE',
    groupCode: 'RC',
    namePt: 'Insuficiencia Respiratoria',
    nameEn: 'Respiratory Failure',
    definition: 'Falencia do sistema respiratorio em manter oxigenacao e/ou ventilacao adequadas.',
    synonyms: ['falencia respiratoria', 'hipoxemia', 'hipercapnia', 'dessaturacao'],
    icd10Codes: ['J96.0', 'J96.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.SYNDROME, value: 'respiratory_failure' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
]

// ============================================
// NC - NEUROLOGICO
// ============================================

export const NEUROLOGICAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'NC_STROKE_SUSPECTED',
    groupCode: 'NC',
    namePt: 'Suspeita de AVC',
    nameEn: 'Suspected Stroke',
    definition: 'Deficit neurologico focal de inicio subito: hemiparesia, afasia, desvio de rima, disartria.',
    synonyms: ['avc', 'derrame', 'lado fraco', 'boca torta', 'fala embolada', 'isquemia cerebral', 'avc isquemico'],
    icd10Codes: ['I64', 'I63.9', 'G45.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.SYNDROME, value: 'stroke' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'nihss',
  },
  {
    code: 'NC_HEADACHE_THUNDERCLAP',
    groupCode: 'NC',
    namePt: 'Cefaleia em Trovoada',
    nameEn: 'Thunderclap Headache',
    definition: 'Cefaleia de inicio subito, intensidade maxima em segundos. Sugere HSA ate prova em contrario.',
    synonyms: ['dor de cabeca forte', 'cefaleia subita', 'a pior dor de cabeca da vida', 'cefaleia explosiva'],
    icd10Codes: ['G44.5', 'I60.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
    defaultCalculatorId: 'nihss',
  },
  {
    code: 'NC_HEADACHE_PRIMARY',
    groupCode: 'NC',
    namePt: 'Cefaleia Primaria',
    nameEn: 'Primary Headache',
    definition: 'Cefaleia sem sinais de alarme: enxaqueca, cefaleia tensional, cefaleia em salvas.',
    synonyms: ['dor de cabeca', 'enxaqueca', 'migrânea', 'cefaleia tensional'],
    icd10Codes: ['G43.9', 'G44.2', 'R51'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'NC_ALTERED_CONSCIOUSNESS',
    groupCode: 'NC',
    namePt: 'Alteracao do Nivel de Consciencia',
    nameEn: 'Altered Level of Consciousness',
    definition: 'Rebaixamento do sensorio: sonolencia, confusao, torpor ou coma.',
    synonyms: ['rebaixamento', 'confusao mental', 'desorientado', 'letargia', 'torpor', 'coma', 'inconsciente'],
    icd10Codes: ['R40.0', 'R40.1', 'R40.2'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'NC_SEIZURE',
    groupCode: 'NC',
    namePt: 'Convulsao',
    nameEn: 'Seizure',
    definition: 'Episodio de atividade eletrica cerebral anormal com manifestacoes motoras, sensoriais ou comportamentais.',
    synonyms: ['crise convulsiva', 'ataque epileptico', 'epilepsia', 'crise', 'tremendo todo'],
    icd10Codes: ['G40.9', 'R56.8'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'NC_VERTIGO',
    groupCode: 'NC',
    namePt: 'Vertigem',
    nameEn: 'Vertigo',
    definition: 'Sensacao de rotacao do ambiente ou de si mesmo. Pode ser periferico (VPPB) ou central.',
    synonyms: ['tontura', 'zonzeira', 'labirintite', 'mundo girando', 'desequilibrio'],
    icd10Codes: ['R42', 'H81.1'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'NC_PARESTHESIA',
    groupCode: 'NC',
    namePt: 'Parestesia / Dormencia',
    nameEn: 'Paresthesia / Numbness',
    definition: 'Sensacao anormal de formigamento, dormencia ou queimacao. Pode indicar lesao neural ou AVC.',
    synonyms: ['formigamento', 'dormencia', 'adormecimento', 'mao dormente', 'pe dormente'],
    icd10Codes: ['R20.2'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'NC_WEAKNESS_FOCAL',
    groupCode: 'NC',
    namePt: 'Fraqueza Focal',
    nameEn: 'Focal Weakness',
    definition: 'Perda de forca em um membro ou hemicorpo. Pode indicar AVC, compressao medular ou miastenia.',
    synonyms: ['fraqueza no braco', 'fraqueza na perna', 'hemiparesia', 'nao consegue levantar o braco'],
    icd10Codes: ['R29.81', 'G81.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'nihss',
  },
]

// ============================================
// GI - GASTROINTESTINAL
// ============================================

export const GASTROINTESTINAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'GI_ABDOMINAL_PAIN_ACUTE',
    groupCode: 'GI',
    namePt: 'Dor Abdominal Aguda',
    nameEn: 'Acute Abdominal Pain',
    definition: 'Dor abdominal de inicio recente (<7 dias) requerendo avaliacao para exclusao de abdome agudo.',
    synonyms: ['dor na barriga', 'dor abdominal', 'dor de barriga', 'colica', 'pontada na barriga'],
    icd10Codes: ['R10.9', 'R10.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.SYNDROME, value: 'acute_abdomen' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'alvarado',
    legacySyndromeCode: 'ACUTE_ABDOMEN',
  },
  {
    code: 'GI_NAUSEA_VOMITING',
    groupCode: 'GI',
    namePt: 'Nauseas e Vomitos',
    nameEn: 'Nausea and Vomiting',
    definition: 'Sensacao de mal-estar epigastrico com ou sem expulsao do conteudo gastrico.',
    synonyms: ['enjoo', 'vomito', 'nausea', 'ânsia', 'vomitando'],
    icd10Codes: ['R11.0', 'R11.2'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'GI_DIARRHEA_ACUTE',
    groupCode: 'GI',
    namePt: 'Diarreia Aguda',
    nameEn: 'Acute Diarrhea',
    definition: 'Aumento da frequencia e/ou fluidez das evacuacoes (<14 dias). Geralmente infeccioso.',
    synonyms: ['diarreia', 'intestino solto', 'evacuacoes liquidas', 'desarranjo', 'gastroenterite'],
    icd10Codes: ['A09', 'K52.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    requiresIsolation: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.RISK, value: 'requires_isolation' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'GI_GI_BLEEDING_UPPER',
    groupCode: 'GI',
    namePt: 'Hemorragia Digestiva Alta',
    nameEn: 'Upper GI Bleeding',
    definition: 'Sangramento originado acima do angulo de Treitz: hematemese, melena.',
    synonyms: ['vomito com sangue', 'hematemese', 'melena', 'fezes pretas', 'sangue no vomito'],
    icd10Codes: ['K92.0', 'K92.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.SYNDROME, value: 'shock' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'glasgow', // Glasgow-Blatchford
  },
  {
    code: 'GI_GI_BLEEDING_LOWER',
    groupCode: 'GI',
    namePt: 'Hemorragia Digestiva Baixa',
    nameEn: 'Lower GI Bleeding',
    definition: 'Sangramento originado abaixo do angulo de Treitz: hematoquezia, enterorragia.',
    synonyms: ['sangue nas fezes', 'hematoquezia', 'enterorragia', 'sangue vermelho vivo nas fezes'],
    icd10Codes: ['K92.2'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'GI_CONSTIPATION',
    groupCode: 'GI',
    namePt: 'Constipacao / Obstipacao',
    nameEn: 'Constipation',
    definition: 'Dificuldade para evacuar ou reducao da frequencia de evacuacoes.',
    synonyms: ['prisao de ventre', 'intestino preso', 'nao evacua', 'fezes ressecadas', 'obstipacao'],
    icd10Codes: ['K59.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'GI_JAUNDICE',
    groupCode: 'GI',
    namePt: 'Ictericia',
    nameEn: 'Jaundice',
    definition: 'Coloracao amarelada de pele e mucosas por acumulo de bilirrubina.',
    synonyms: ['amarelao', 'pele amarela', 'olhos amarelos', 'ictericia'],
    icd10Codes: ['R17'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
      { category: TagCategory.AGE, value: 'neonate' },
    ],
    defaultCalculatorId: 'meld',
  },
  {
    code: 'GI_DYSPHAGIA',
    groupCode: 'GI',
    namePt: 'Disfagia',
    nameEn: 'Dysphagia',
    definition: 'Dificuldade para engolir alimentos solidos e/ou liquidos.',
    synonyms: ['dificuldade para engolir', 'engasgo', 'comida entala', 'nao consegue engolir'],
    icd10Codes: ['R13.1', 'R13.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'gastrointestinal' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
]

// ============================================
// INF - INFECCIOSO
// ============================================

export const INFECTIOUS_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'INF_FEVER_NO_FOCUS_ADULT',
    groupCode: 'INF',
    namePt: 'Febre sem Foco (Adulto)',
    nameEn: 'Fever Without Source (Adult)',
    definition: 'Temperatura >= 38C sem foco infeccioso evidente ao exame inicial.',
    synonyms: ['febre', 'febre alta', 'temperatura', 'corpo quente', 'calafrios'],
    icd10Codes: ['R50.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
    defaultCalculatorId: 'qsofa',
  },
  {
    code: 'INF_FEVER_PEDIATRIC',
    groupCode: 'INF',
    namePt: 'Febre Pediatrica',
    nameEn: 'Pediatric Fever',
    definition: 'Febre em crianca, especialmente se < 3 meses (alto risco de infeccao bacteriana grave).',
    synonyms: ['febre na crianca', 'bebe com febre', 'crianca quente'],
    icd10Codes: ['R50.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'pediatric' },
      { category: TagCategory.AGE, value: 'neonate' },
    ],
  },
  {
    code: 'INF_SEPSIS_SUSPECTED',
    groupCode: 'INF',
    namePt: 'Suspeita de Sepse',
    nameEn: 'Suspected Sepsis',
    definition: 'Disfuncao organica potencialmente fatal causada por resposta desregulada a infeccao.',
    synonyms: ['infeccao generalizada', 'septicemia', 'choque septico', 'infeccao grave'],
    icd10Codes: ['A41.9', 'R65.20', 'R65.21'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.SYNDROME, value: 'sepsis' },
      { category: TagCategory.SYNDROME, value: 'shock' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'qsofa',
  },
  {
    code: 'INF_FEVER_WITH_RASH',
    groupCode: 'INF',
    namePt: 'Febre com Rash',
    nameEn: 'Fever with Rash',
    definition: 'Febre acompanhada de lesoes cutaneas. Considerar meningococcemia, dengue, sarampo.',
    synonyms: ['febre com manchas', 'febre com bolinhas', 'exantema febril'],
    icd10Codes: ['R21', 'R50.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    requiresIsolation: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.SYSTEM, value: 'dermatological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'requires_isolation' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'INF_DENGUE_SUSPECTED',
    groupCode: 'INF',
    namePt: 'Suspeita de Dengue',
    nameEn: 'Suspected Dengue',
    definition: 'Febre + dor retro-orbital + mialgia + artralgia em area endemica. Atentar para sinais de alarme.',
    synonyms: ['dengue', 'febre da dengue', 'dengue hemorragica', 'febre quebra-ossos'],
    icd10Codes: ['A90', 'A91'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'INF_UTI',
    groupCode: 'INF',
    namePt: 'Infeccao Urinaria',
    nameEn: 'Urinary Tract Infection',
    definition: 'Infeccao do trato urinario: cistite ou pielonefrite.',
    synonyms: ['infeccao urinaria', 'cistite', 'pielonefrite', 'infeccao de urina', 'itu'],
    icd10Codes: ['N39.0', 'N10'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'INF_CELLULITIS',
    groupCode: 'INF',
    namePt: 'Celulite / Erisipela',
    nameEn: 'Cellulitis / Erysipelas',
    definition: 'Infeccao bacteriana de pele e tecido subcutaneo.',
    synonyms: ['celulite', 'erisipela', 'pele vermelha', 'infeccao de pele', 'vermelhidao na perna'],
    icd10Codes: ['L03.9', 'A46'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.SYSTEM, value: 'dermatological' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'INF_PNEUMONIA',
    groupCode: 'INF',
    namePt: 'Pneumonia',
    nameEn: 'Pneumonia',
    definition: 'Infeccao do parenquima pulmonar com infiltrado ao raio-x.',
    synonyms: ['pneumonia', 'infeccao pulmonar', 'pulmao inflamado'],
    icd10Codes: ['J18.9', 'J15.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'curb-65',
  },
]

// ============================================
// GU - GENITURINARIO
// ============================================

export const GENITOURINARY_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'GU_RENAL_COLIC',
    groupCode: 'GU',
    namePt: 'Colica Renal / Nefrolitiase',
    nameEn: 'Renal Colic / Nephrolithiasis',
    definition: 'Dor em flanco com irradiacao para regiao inguinal, tipica de obstrucao ureteral por calculo.',
    synonyms: ['colica renal', 'pedra no rim', 'calculo renal', 'dor no rim', 'nefrolitiase'],
    icd10Codes: ['N23', 'N20.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'GU_URINARY_RETENTION',
    groupCode: 'GU',
    namePt: 'Retencao Urinaria',
    nameEn: 'Urinary Retention',
    definition: 'Incapacidade de esvaziar a bexiga apesar da vontade de urinar. Comum em HPB.',
    synonyms: ['nao consegue urinar', 'retencao urinaria', 'bexiga cheia', 'urina presa'],
    icd10Codes: ['R33.9'],
    isTimeSensitive: true,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'GU_HEMATURIA',
    groupCode: 'GU',
    namePt: 'Hematuria',
    nameEn: 'Hematuria',
    definition: 'Presenca de sangue na urina, macro ou microscopica.',
    synonyms: ['sangue na urina', 'urina com sangue', 'urina vermelha', 'hematuria'],
    icd10Codes: ['R31.9', 'R31.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'GU_DYSURIA',
    groupCode: 'GU',
    namePt: 'Disuria',
    nameEn: 'Dysuria',
    definition: 'Dor ou ardencia ao urinar. Comum em infeccoes urinarias.',
    synonyms: ['ardencia ao urinar', 'dor ao urinar', 'queimacao ao urinar', 'disuria'],
    icd10Codes: ['R30.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'GU_TESTICULAR_PAIN',
    groupCode: 'GU',
    namePt: 'Dor Testicular',
    nameEn: 'Testicular Pain',
    definition: 'Dor no testiculo. Considerar torcao testicular (emergencia) em jovens.',
    synonyms: ['dor no testiculo', 'dor no saco', 'testiculo inchado', 'dor escrotal'],
    icd10Codes: ['N50.8'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
]

// ============================================
// MSK - MUSCULOESQUELETICO
// ============================================

export const MUSCULOSKELETAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'MSK_LOW_BACK_PAIN',
    groupCode: 'MSK',
    namePt: 'Lombalgia',
    nameEn: 'Low Back Pain',
    definition: 'Dor na regiao lombar. Excluir red flags: sintomas neurologicos, trauma, cancer.',
    synonyms: ['dor nas costas', 'dor lombar', 'lombalgia', 'coluna travada', 'dor na coluna'],
    icd10Codes: ['M54.5', 'M54.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'musculoskeletal' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'MSK_JOINT_PAIN',
    groupCode: 'MSK',
    namePt: 'Dor Articular',
    nameEn: 'Joint Pain',
    definition: 'Dor em uma ou mais articulacoes. Considerar artrite septica, gota, trauma.',
    synonyms: ['dor no joelho', 'dor no ombro', 'artralgia', 'dor nas juntas', 'articulacao inchada'],
    icd10Codes: ['M25.5'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'musculoskeletal' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'MSK_LIMB_PAIN_TRAUMA',
    groupCode: 'MSK',
    namePt: 'Dor em Membro pos-Trauma',
    nameEn: 'Limb Pain Post-Trauma',
    definition: 'Dor em membro apos trauma. Avaliar fratura, luxacao, lesao ligamentar.',
    synonyms: ['trauma no braco', 'trauma na perna', 'torci o pe', 'torci o pulso', 'pancada'],
    icd10Codes: ['S00-T88'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'musculoskeletal' },
      { category: TagCategory.SYSTEM, value: 'traumatic' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'MSK_NECK_PAIN',
    groupCode: 'MSK',
    namePt: 'Cervicalgia',
    nameEn: 'Neck Pain',
    definition: 'Dor na regiao cervical. Excluir rigidez de nuca (meningite), trauma cervical.',
    synonyms: ['dor no pescoco', 'cervicalgia', 'torcicolo', 'pescoco travado'],
    icd10Codes: ['M54.2'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'musculoskeletal' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
]

// ============================================
// PSI - PSIQUIATRICO
// ============================================

export const PSYCHIATRIC_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'PSI_SUICIDAL_IDEATION',
    groupCode: 'PSI',
    namePt: 'Ideacao Suicida',
    nameEn: 'Suicidal Ideation',
    definition: 'Pensamentos de morte ou suicidio com ou sem plano estruturado.',
    synonyms: ['quer se matar', 'pensando em suicidio', 'ideacao suicida', 'tentativa de suicidio'],
    icd10Codes: ['R45.851', 'X71-X83'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'psychiatric' },
      { category: TagCategory.SYNDROME, value: 'psychiatric_emergency' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'phq-9',
  },
  {
    code: 'PSI_PSYCHOMOTOR_AGITATION',
    groupCode: 'PSI',
    namePt: 'Agitacao Psicomotora',
    nameEn: 'Psychomotor Agitation',
    definition: 'Estado de excitacao psiquica com inquietacao motora. Pode requerer contencao.',
    synonyms: ['agitado', 'agressivo', 'surto', 'descontrolado', 'violento'],
    icd10Codes: ['R45.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'psychiatric' },
      { category: TagCategory.SYNDROME, value: 'psychiatric_emergency' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'PSI_ANXIETY_PANIC',
    groupCode: 'PSI',
    namePt: 'Ansiedade / Panico',
    nameEn: 'Anxiety / Panic',
    definition: 'Crise de ansiedade ou panico com sintomas somaticos: taquicardia, dispneia, sudorese.',
    synonyms: ['crise de ansiedade', 'ataque de panico', 'ansiedade', 'nervoso', 'crise de nervos'],
    icd10Codes: ['F41.0', 'F41.1'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'psychiatric' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'PSI_PSYCHOSIS',
    groupCode: 'PSI',
    namePt: 'Psicose Aguda',
    nameEn: 'Acute Psychosis',
    definition: 'Perda de contato com a realidade: alucinacoes, delirios, comportamento bizarro.',
    synonyms: ['surto psicotico', 'alucinando', 'delirando', 'psicose', 'esquizofrenia'],
    icd10Codes: ['F23.9', 'F20.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'psychiatric' },
      { category: TagCategory.SYNDROME, value: 'psychiatric_emergency' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
]

// ============================================
// TR - TRAUMA
// ============================================

export const TRAUMA_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'TR_POLYTRAUMA',
    groupCode: 'TR',
    namePt: 'Politrauma',
    nameEn: 'Polytrauma',
    definition: 'Multiplas lesoes traumaticas, pelo menos uma potencialmente fatal.',
    synonyms: ['acidente grave', 'atropelamento', 'colisao', 'politraumatizado'],
    icd10Codes: ['T07'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'traumatic' },
      { category: TagCategory.SYNDROME, value: 'trauma' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'TR_HEAD_TRAUMA',
    groupCode: 'TR',
    namePt: 'Trauma Cranioencefalico',
    nameEn: 'Traumatic Brain Injury',
    definition: 'Trauma na cabeca com ou sem perda de consciencia. Avaliar sinais de alarme.',
    synonyms: ['bateu a cabeca', 'tce', 'pancada na cabeca', 'trauma na cabeca', 'concussao'],
    icd10Codes: ['S06.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'traumatic' },
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.SYNDROME, value: 'trauma' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'TR_PENETRATING_TRAUMA',
    groupCode: 'TR',
    namePt: 'Trauma Penetrante',
    nameEn: 'Penetrating Trauma',
    definition: 'Lesao por arma branca ou arma de fogo com violacao de cavidades.',
    synonyms: ['ferimento por arma de fogo', 'faf', 'facada', 'ferimento por arma branca', 'fab', 'esfaqueado', 'baleado'],
    icd10Codes: ['T14.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'traumatic' },
      { category: TagCategory.SYNDROME, value: 'trauma' },
      { category: TagCategory.SYNDROME, value: 'shock' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'TR_FALL_ELDERLY',
    groupCode: 'TR',
    namePt: 'Queda em Idoso',
    nameEn: 'Fall in Elderly',
    definition: 'Queda em paciente >= 65 anos. Alto risco de fraturas e TCE.',
    synonyms: ['idoso caiu', 'queda da propria altura', 'caiu em casa'],
    icd10Codes: ['W19'],
    isTimeSensitive: false,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'traumatic' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'TR_BURNS',
    groupCode: 'TR',
    namePt: 'Queimadura',
    nameEn: 'Burns',
    definition: 'Lesao termica da pele. Classificar por grau e superficie corporal.',
    synonyms: ['queimadura', 'queimou', 'escaldou', 'agua quente'],
    icd10Codes: ['T30.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'traumatic' },
      { category: TagCategory.SYSTEM, value: 'dermatological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
]

// ============================================
// TOX - TOXICOLOGICO
// ============================================

export const TOXICOLOGICAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'TOX_OVERDOSE',
    groupCode: 'TOX',
    namePt: 'Overdose / Intoxicacao Exogena',
    nameEn: 'Overdose / Poisoning',
    definition: 'Exposicao a substancia toxica em dose potencialmente lesiva.',
    synonyms: ['overdose', 'intoxicacao', 'envenenamento', 'tomou remedio demais', 'ingeriu veneno'],
    icd10Codes: ['T50.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'toxicological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'TOX_ALCOHOL_INTOX',
    groupCode: 'TOX',
    namePt: 'Intoxicacao Alcoolica',
    nameEn: 'Alcohol Intoxication',
    definition: 'Intoxicacao aguda por etanol. Avaliar nivel de consciencia e complicacoes.',
    synonyms: ['bebado', 'embriagado', 'intoxicacao alcoolica', 'bebeu demais', 'coma alcoolico'],
    icd10Codes: ['F10.0', 'T51.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'toxicological' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
    defaultCalculatorId: 'glasgow',
  },
  {
    code: 'TOX_DRUG_ABUSE',
    groupCode: 'TOX',
    namePt: 'Uso de Drogas Ilicitas',
    nameEn: 'Illicit Drug Use',
    definition: 'Intoxicacao ou efeitos adversos de drogas ilicitas: cocaina, crack, maconha, ecstasy.',
    synonyms: ['usou droga', 'cocaina', 'crack', 'maconha', 'ecstasy', 'noia'],
    icd10Codes: ['F14.0', 'F15.0', 'F12.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'toxicological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
    defaultCalculatorId: 'glasgow',
  },
]

// ============================================
// ENV - AMBIENTAL
// ============================================

export const ENVIRONMENTAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'ENV_SNAKE_BITE',
    groupCode: 'ENV',
    namePt: 'Picada de Cobra',
    nameEn: 'Snake Bite',
    definition: 'Acidente ofidico. Identificar a cobra se possivel para orientar soroterapia.',
    synonyms: ['picada de cobra', 'mordida de cobra', 'acidente ofidico', 'cobra picou'],
    icd10Codes: ['T63.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'environmental' },
      { category: TagCategory.SYSTEM, value: 'toxicological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'ENV_SCORPION_STING',
    groupCode: 'ENV',
    namePt: 'Picada de Escorpiao',
    nameEn: 'Scorpion Sting',
    definition: 'Acidente escorpionico. Maior gravidade em criancas.',
    synonyms: ['picada de escorpiao', 'escorpiao picou', 'acidente escorpionico'],
    icd10Codes: ['T63.2'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'environmental' },
      { category: TagCategory.SYSTEM, value: 'toxicological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'ENV_BEE_STING',
    groupCode: 'ENV',
    namePt: 'Picada de Abelha / Vespa',
    nameEn: 'Bee / Wasp Sting',
    definition: 'Picada de himenoptero. Atentar para anafilaxia em pacientes alergicos.',
    synonyms: ['picada de abelha', 'picada de vespa', 'picada de marimbondo', 'abelha picou'],
    icd10Codes: ['T63.4'],
    isTimeSensitive: true,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'environmental' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'ENV_DROWNING',
    groupCode: 'ENV',
    namePt: 'Afogamento',
    nameEn: 'Drowning',
    definition: 'Submersao ou imersao em liquido com comprometimento respiratorio.',
    synonyms: ['afogamento', 'quase afogou', 'engoliu agua', 'submersao'],
    icd10Codes: ['T75.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'environmental' },
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'ENV_HEAT_STROKE',
    groupCode: 'ENV',
    namePt: 'Insolacao / Hipertermia',
    nameEn: 'Heat Stroke',
    definition: 'Hipertermia grave (>40C) com disfuncao do SNC. Emergencia medica.',
    synonyms: ['insolacao', 'calor excessivo', 'hipertermia', 'golpe de calor'],
    icd10Codes: ['T67.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'environmental' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'ENV_HYPOTHERMIA',
    groupCode: 'ENV',
    namePt: 'Hipotermia',
    nameEn: 'Hypothermia',
    definition: 'Temperatura corporal central < 35C.',
    synonyms: ['hipotermia', 'frio', 'congelamento', 'temperatura baixa'],
    icd10Codes: ['T68'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'environmental' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
      { category: TagCategory.AGE, value: 'neonate' },
    ],
  },
]

// ============================================
// OBG - OBSTETRICO / GINECOLOGICO
// ============================================

export const OBGYN_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'OBG_VAGINAL_BLEEDING_PREGNANT',
    groupCode: 'OBG',
    namePt: 'Sangramento Vaginal na Gestacao',
    nameEn: 'Vaginal Bleeding in Pregnancy',
    definition: 'Sangramento vaginal durante a gravidez. Considerar aborto, gravidez ectopica, DPP, PP.',
    synonyms: ['sangramento na gravidez', 'gravida sangrando', 'perda de sangue gestante'],
    icd10Codes: ['O20.9', 'O46.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'obstetric' },
      { category: TagCategory.CONTEXT, value: 'pregnancy' },
    ],
  },
  {
    code: 'OBG_LABOR',
    groupCode: 'OBG',
    namePt: 'Trabalho de Parto',
    nameEn: 'Labor',
    definition: 'Contracoes uterinas regulares com dilatacao cervical progressiva.',
    synonyms: ['em trabalho de parto', 'contracoes', 'dor de parto', 'vai nascer'],
    icd10Codes: ['O80', 'O62.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'obstetric' },
      { category: TagCategory.CONTEXT, value: 'pregnancy' },
    ],
    defaultCalculatorId: 'pregnancy-dates',
  },
  {
    code: 'OBG_PELVIC_PAIN',
    groupCode: 'OBG',
    namePt: 'Dor Pelvica',
    nameEn: 'Pelvic Pain',
    definition: 'Dor na regiao pelvica em mulher. Considerar DIP, cisto ovariano, gravidez ectopica.',
    synonyms: ['dor na pelve', 'dor no pe da barriga', 'dor pelvica', 'dor no utero'],
    icd10Codes: ['R10.2'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'OBG_VAGINAL_DISCHARGE',
    groupCode: 'OBG',
    namePt: 'Corrimento Vaginal',
    nameEn: 'Vaginal Discharge',
    definition: 'Secrecao vaginal anormal em quantidade, cor ou odor.',
    synonyms: ['corrimento', 'secrecao vaginal', 'leucorreia'],
    icd10Codes: ['N89.8'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'genitourinary' },
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
]

// ============================================
// PED - PEDIATRICO
// ============================================

export const PEDIATRIC_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'PED_RESPIRATORY_DISTRESS',
    groupCode: 'PED',
    namePt: 'Desconforto Respiratorio Pediatrico',
    nameEn: 'Pediatric Respiratory Distress',
    definition: 'Sinais de dificuldade respiratoria em crianca: tiragem, batimento de asa nasal, gemencia.',
    synonyms: ['crianca com falta de ar', 'bebe sufocando', 'bronquiolite', 'crupe'],
    icd10Codes: ['J96.0', 'J21.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'respiratory' },
      { category: TagCategory.SYNDROME, value: 'respiratory_failure' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'pediatric' },
      { category: TagCategory.AGE, value: 'neonate' },
    ],
  },
  {
    code: 'PED_DEHYDRATION',
    groupCode: 'PED',
    namePt: 'Desidratacao Pediatrica',
    nameEn: 'Pediatric Dehydration',
    definition: 'Perda de liquidos corporais em crianca, geralmente por vomitos/diarreia.',
    synonyms: ['crianca desidratada', 'bebe desidratado', 'nao faz xixi', 'labios secos'],
    icd10Codes: ['E86.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'metabolic' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'pediatric' },
      { category: TagCategory.AGE, value: 'neonate' },
    ],
  },
  {
    code: 'PED_FEBRILE_SEIZURE',
    groupCode: 'PED',
    namePt: 'Convulsao Febril',
    nameEn: 'Febrile Seizure',
    definition: 'Crise convulsiva associada a febre em crianca de 6 meses a 5 anos.',
    synonyms: ['convulsao por febre', 'ataque com febre', 'crise febril'],
    icd10Codes: ['R56.0'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'neurological' },
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'glasgow',
  },
]

// ============================================
// MET - METABOLICO
// ============================================

export const METABOLIC_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'MET_DIABETIC_EMERGENCY',
    groupCode: 'MET',
    namePt: 'Emergencia Diabetica',
    nameEn: 'Diabetic Emergency',
    definition: 'Cetoacidose diabetica ou estado hiperglicemico hiperosmolar.',
    synonyms: ['diabetes descompensado', 'glicose alta', 'cetoacidose', 'coma diabetico'],
    icd10Codes: ['E10.1', 'E11.0', 'E11.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'metabolic' },
      { category: TagCategory.SYNDROME, value: 'diabetic_emergency' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'MET_HYPOGLYCEMIA',
    groupCode: 'MET',
    namePt: 'Hipoglicemia',
    nameEn: 'Hypoglycemia',
    definition: 'Glicemia < 70mg/dL com sintomas: sudorese, tremor, confusao.',
    synonyms: ['glicose baixa', 'hipoglicemia', 'tontura por diabetes', 'passou mal diabetico'],
    icd10Codes: ['E16.2'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'metabolic' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'MET_ELECTROLYTE_DISORDER',
    groupCode: 'MET',
    namePt: 'Disturbio Eletrolitico',
    nameEn: 'Electrolyte Disorder',
    definition: 'Alteracao de sodio, potassio, calcio ou magnesio com repercussao clinica.',
    synonyms: ['potassio alto', 'potassio baixo', 'sodio baixo', 'caimbras'],
    icd10Codes: ['E87.6', 'E87.1', 'E87.8'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'metabolic' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
]

// ============================================
// DERM - DERMATOLOGICO
// ============================================

export const DERMATOLOGICAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'DERM_RASH',
    groupCode: 'DERM',
    namePt: 'Rash / Exantema',
    nameEn: 'Rash / Exanthem',
    definition: 'Erupcao cutanea difusa. Pode ser alergica, infecciosa ou autoimune.',
    synonyms: ['manchas na pele', 'rash', 'alergia de pele', 'bolinhas', 'exantema'],
    icd10Codes: ['R21'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'dermatological' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'DERM_URTICARIA',
    groupCode: 'DERM',
    namePt: 'Urticaria',
    nameEn: 'Urticaria',
    definition: 'Placas eritematosas elevadas pruriginosas. Pode evoluir para anafilaxia.',
    synonyms: ['urticaria', 'coceira', 'alergia', 'placas vermelhas', 'vergoes'],
    icd10Codes: ['L50.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'dermatological' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'DERM_ANAPHYLAXIS',
    groupCode: 'DERM',
    namePt: 'Anafilaxia',
    nameEn: 'Anaphylaxis',
    definition: 'Reacao alergica grave sistemica com risco de morte.',
    synonyms: ['choque anafilatico', 'alergia grave', 'reacao alergica', 'inchou tudo'],
    icd10Codes: ['T78.2'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'dermatological' },
      { category: TagCategory.SYNDROME, value: 'shock' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.RISK, value: 'potentially_life_threatening' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
]

// ============================================
// OFT - OFTALMOLOGICO
// ============================================

export const OPHTHALMOLOGICAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'OFT_EYE_PAIN',
    groupCode: 'OFT',
    namePt: 'Dor Ocular',
    nameEn: 'Eye Pain',
    definition: 'Dor no olho. Considerar glaucoma agudo, uveite, corpo estranho.',
    synonyms: ['dor no olho', 'olho doendo', 'pressao no olho'],
    icd10Codes: ['H57.1'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'ophthalmological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'OFT_VISION_LOSS',
    groupCode: 'OFT',
    namePt: 'Perda Visual',
    nameEn: 'Vision Loss',
    definition: 'Reducao ou perda da visao. Pode indicar oclusao vascular, descolamento de retina.',
    synonyms: ['nao enxerga', 'visao embaçada', 'cegueira', 'perdeu a visao'],
    icd10Codes: ['H54.9'],
    isTimeSensitive: true,
    isHighAcuity: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'ophthalmological' },
      { category: TagCategory.RISK, value: 'high_acuity' },
      { category: TagCategory.RISK, value: 'time_sensitive' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'OFT_RED_EYE',
    groupCode: 'OFT',
    namePt: 'Olho Vermelho',
    nameEn: 'Red Eye',
    definition: 'Hiperemia conjuntival. Pode ser conjuntivite, uveite, glaucoma.',
    synonyms: ['olho vermelho', 'conjuntivite', 'olho irritado'],
    icd10Codes: ['H10.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    requiresIsolation: true,
    tags: [
      { category: TagCategory.SYSTEM, value: 'ophthalmological' },
      { category: TagCategory.RISK, value: 'requires_isolation' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
]

// ============================================
// ORL - ORL / ODONTOLOGICO
// ============================================

export const ENT_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'ORL_SORE_THROAT',
    groupCode: 'ORL',
    namePt: 'Odinofagia / Dor de Garganta',
    nameEn: 'Sore Throat',
    definition: 'Dor ao engolir. Considerar faringite, amigdalite, abscesso.',
    synonyms: ['dor de garganta', 'garganta inflamada', 'dificuldade para engolir', 'amigdalite'],
    icd10Codes: ['R07.0', 'J02.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'otorhinolaryngological' },
      { category: TagCategory.SYSTEM, value: 'infectious' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
    defaultCalculatorId: 'centor-mcisaac',
  },
  {
    code: 'ORL_EPISTAXIS',
    groupCode: 'ORL',
    namePt: 'Epistaxe',
    nameEn: 'Epistaxis',
    definition: 'Sangramento nasal. Pode ser anterior (comum) ou posterior (grave).',
    synonyms: ['sangramento nasal', 'nariz sangrando', 'sangue pelo nariz'],
    icd10Codes: ['R04.0'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'otorhinolaryngological' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'ORL_EAR_PAIN',
    groupCode: 'ORL',
    namePt: 'Otalgia',
    nameEn: 'Ear Pain',
    definition: 'Dor no ouvido. Pode ser otite externa, media ou dor referida.',
    synonyms: ['dor de ouvido', 'ouvido doendo', 'otite', 'ouvido inflamado'],
    icd10Codes: ['H92.0', 'H66.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'otorhinolaryngological' },
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
  {
    code: 'ORL_DENTAL_PAIN',
    groupCode: 'ORL',
    namePt: 'Dor Dental',
    nameEn: 'Dental Pain',
    definition: 'Dor de dente. Pode indicar carie, abscesso, trauma.',
    synonyms: ['dor de dente', 'dente doendo', 'abscesso dental', 'dente inflamado'],
    icd10Codes: ['K08.8'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.SYSTEM, value: 'otorhinolaryngological' },
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
]

// ============================================
// GEN - GERAL
// ============================================

export const GENERAL_COMPLAINTS: ChiefComplaintSeed[] = [
  {
    code: 'GEN_FATIGUE',
    groupCode: 'GEN',
    namePt: 'Fadiga / Astenia',
    nameEn: 'Fatigue / Asthenia',
    definition: 'Sensacao de cansaco ou fraqueza sem causa evidente.',
    synonyms: ['cansaco', 'fraqueza', 'astenia', 'sem energia', 'prostrado'],
    icd10Codes: ['R53.83', 'R53.1'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'GEN_MALAISE',
    groupCode: 'GEN',
    namePt: 'Mal-estar Geral',
    nameEn: 'General Malaise',
    definition: 'Sensacao de desconforto ou indisposicao sem sintomas especificos.',
    synonyms: ['mal-estar', 'passando mal', 'indisposto', 'nao esta bem'],
    icd10Codes: ['R53.81'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.AGE, value: 'adult' },
    ],
  },
  {
    code: 'GEN_WEIGHT_LOSS',
    groupCode: 'GEN',
    namePt: 'Perda de Peso',
    nameEn: 'Weight Loss',
    definition: 'Perda de peso involuntaria. Pode indicar neoplasia, infeccao, endocrinopatia.',
    synonyms: ['emagrecimento', 'perda de peso', 'emagreceu muito'],
    icd10Codes: ['R63.4'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'elderly' },
    ],
  },
  {
    code: 'GEN_LYMPHADENOPATHY',
    groupCode: 'GEN',
    namePt: 'Linfonodomegalia',
    nameEn: 'Lymphadenopathy',
    definition: 'Aumento dos linfonodos. Pode ser reacional, infeccioso ou neoplasico.',
    synonyms: ['ingua', 'caroço', 'gânglio', 'linfonodo aumentado'],
    icd10Codes: ['R59.9'],
    isTimeSensitive: false,
    isHighAcuity: false,
    tags: [
      { category: TagCategory.AGE, value: 'adult' },
      { category: TagCategory.AGE, value: 'pediatric' },
    ],
  },
]

// ============================================
// ALL COMPLAINTS CONSOLIDATED
// ============================================

export const ALL_COMPLAINTS: ChiefComplaintSeed[] = [
  ...CARDIOVASCULAR_COMPLAINTS,
  ...RESPIRATORY_COMPLAINTS,
  ...NEUROLOGICAL_COMPLAINTS,
  ...GASTROINTESTINAL_COMPLAINTS,
  ...INFECTIOUS_COMPLAINTS,
  ...GENITOURINARY_COMPLAINTS,
  ...MUSCULOSKELETAL_COMPLAINTS,
  ...PSYCHIATRIC_COMPLAINTS,
  ...TRAUMA_COMPLAINTS,
  ...TOXICOLOGICAL_COMPLAINTS,
  ...ENVIRONMENTAL_COMPLAINTS,
  ...OBGYN_COMPLAINTS,
  ...PEDIATRIC_COMPLAINTS,
  ...METABOLIC_COMPLAINTS,
  ...DERMATOLOGICAL_COMPLAINTS,
  ...OPHTHALMOLOGICAL_COMPLAINTS,
  ...ENT_COMPLAINTS,
  ...GENERAL_COMPLAINTS,
]

// Total: 100+ complaints
console.log(`Total chief complaints: ${ALL_COMPLAINTS.length}`)
